name: sonar_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  go_router: ^17.0.1
  geolocator: ^14.0.2
  intl_phone_field: ^3.2.0
  maplibre_gl: ^0.25.0
  google_fonts: ^8.0.0
  json_annotation: ^4.9.0
  file_picker: ^10.3.8
  image: ^4.7.2
  image_picker: ^1.1.2
  http: ^1.6.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.4
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
